apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-frontend
  labels:
    app: hospital-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-frontend
  template:
    metadata:
      labels:
        app: hospital-frontend
    spec:
      containers:
        - name: hospital-frontend
          image: YOUR_REGISTRY/hospital-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: hospital-frontend-service
spec:
  selector:
    app: hospital-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80